apiVersion: v1
kind: ConfigMap
metadata:
  name: todoapi-config
data:
  backendserviceurl: http://todobackend-service:18080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapi-deployment
  labels:
    app : todoapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todoapi
  template:
    metadata:
      labels:
        app: todoapi
    spec:
      containers:
      - name: todoapi
        image: kdkanishka/todo-api:1.2
        env:
          - name: BACKEND_SERVICE
            valueFrom:
              configMapKeyRef:
                name : todoapi-config
                key: backendserviceurl
          - name: ENV
            value: PROD
          - name: QUARKUS_PROFILE
            value: PROD
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: todoapi-service
spec:
  # type: NodePort
  selector:
    app: todoapi
  ports:
  - port: 9090
    targetPort: 9090
    protocol: TCP
